### ISSUE TITLE
Make EVERYTHING Escapable 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/lpp-campaign#4]
LPPCampaignFactory, LPPMilestoneFactory and every other contract that exists in our system needs to be escapable (so when crazy people send tokens to the contracts we can get them out).

I am happy to be the EscapeHatchCaller and the Giveth Multisig should be the destination.

my address: 0x839395e20bbB182fa440d08F850E6c7A8f6F0780

Giveth Multisig: 0x8f951903c9360345b4e1b536c7f5ae8f88a64e79

**Comment by perissology** [comment]
I'll add this to all contracts except for `LPPMilestone`.

adding to `LPPMilestone` will make the contract owned, and will affect the dapp propose milestone flow. There is already a way to collect eth from that contract, and I'll add a method to collect tokens as well. 

The only question is who should be able to collect the tokens for `LPPMilestone`? only the recipient can collect eth. I'd say that the recipient should be able to collect the tokens on that contract as well

**Comment by GriffGreen** [comment]
I agree. Its their contract, if someone sends tokens to it (Think OMG Airdrop), they should get those tokens.
